### ISSUE TITLE
CD'S and Isos are not detected

### ISSUE THREAD

**Issue by CamJRP** [flathub/net.openra.OpenRA#15]
Issue: CD and Isos are not detected in advanced install or to add content
OS: Linux Mint 20.1
Expected behavior: Mounted ISOS should be recognized by the automatic installer or in manage content.

**Comment by Unrud** [comment]
It requires more holes in the sandbox. Not sure if this should be allowed by default. To grant access temporarily run:

```
flatpak run --filesystem=/media:ro net.openra.OpenRA
```

**Comment by CamJRP** [comment]
It did not work :(

**Comment by CamJRP** [comment]
It worked with with CDemu (the linux version of course). But the Allied Disc remains undetected :(.

Can you please tell me what would be the command line to replicate this same process in Dune and Tiberian Dawn?

**Comment by CamJRP** [comment]
Finally managed to solve the issue for Red Alert and Tiberian Dawn.
The only game with i still having issues is Dune 2000; it detects the iso or the emulated cd but it does not install the music ¿Does anyone knows a work around for this?

**Comment by jena-s-lab** [comment]
> Finally managed to solve the issue for Red Alert and Tiberian Dawn.

Mmmm okay, but how ????

**Comment by CamJRP** [comment]
> > Finally managed to solve the issue for Red Alert and Tiberian Dawn.
> 
> Mmmm okay, but how ????

Using flatseal to give the permissions

**Comment by johnhamelink** [comment]
I was able to import the Definitive Edition DVD by running:

```
sudo flatpak override --filesystem=/run/media net.openra.OpenRA
```

Where `/run/media` is where the CD was mounted. Be sure to restart the game after running the above. I do think this override should make its way into the default package

**Comment by ssokolow** [comment]
I used Flatseal to grant `/media:ro` on my Kubuntu 20.04 LTS setup before even launching it the first time and it doesn't see that my Red Alert 95: Allied Disc from the Worldwide Warfare bundle is mounted at `/media/ssokolow/CD1`.

This whole automated approach is a big pain compared to something like CorsixTH, where I just copied the requested folder to `/srv/fservroot/games/...` and used the provided file browser.

**Comment by ssokolow** [comment]
Huh. Despite it requiring more work for OpenRA to extract the assets, my C&C: The First Decade DVD *was* detected correctly, as were the Counterstrike and Aftermath discs from the Worldwide Warfare pack. (Speaking of, it's [this](https://www.mobygames.com/game/command-conquer-worldwide-warfare) pack from 1998.)

I wonder if the Worldwide Warfare version of the Allied Disc has some patches pre-applied and that threw off what it's looking for.

(They're still copyright 1996, as opposed to the "1995, 1996" on the C&C discs in the Worldwide Warfare pack and I don't see any sort of marking in the vein of "v1.01" on them, so I assumed they were just a later pressing of the same discs.)

**Comment by ssokolow** [comment]
...OK, that's interesting. It detects my Dune 2000 disc, and says it's going to pull in the Base Game Files, Game Music, and Campaign Briefings, but doesn't pull in the Game Music no matter how many times I go back around for another try and there's no error message.

**Comment by ssokolow** [comment]
Aha! It did copy them into place but, for some reason, while doing so, it renamed `WAITGAME.AUD` to `WAITGAME.A`. Manually renaming it back causes the music to show as installed.

**Comment by Mailaender** [comment]
> Worldwide Warfare pack

I assume they changed the installers for this bundle. You need to create a new https://github.com/OpenRA/OpenRA/tree/bleed/mods/ra/installer The https://github.com/OpenRA/OpenRA/wiki/Utility has functions to determine byte offsets from the installers used previously.
