### ISSUE TITLE
[FRQ] Add KKnD

### ISSUE THREAD

**Issue by Zlopez** [flathub/net.openra.OpenRA#4]
Hi,

I noticed that the recently released [KKnD](https://github.com/IceReaper/KKnD) is missing in openRA.

It is possible to add it?

**Comment by Unrud** [comment]
> I noticed that the recently released [KKnD](https://github.com/IceReaper/KKnD) is missing in openRA.

I think that it would be better to package it separately. Event ra2, cnc and d2k shouldn't be bundled together, like the official AppImage releases.

**Comment by Zlopez** [comment]
This sounds reasonable.
