### ISSUE TITLE
heads up: next playtest and release will use Roslyn compiler and have new dependencies

### ISSUE THREAD

**Issue by fusion809** [flathub/net.openra.OpenRA#6]
Just thought I'd give you some warning, in case you're unaware of this. The next playtest and release of OpenRA is set to use the Roslyn compiler, which requires Mono 5.10 or later, preferably 5.12 or later. It also requires MSBuild.

**Comment by Unrud** [comment]
Fixed in 38daa0b6b78b3559886aab331ecdc0d1fd0ecd0b
