### ISSUE TITLE
GLXBadContext on openSUSE 15.1 with NVIDIA drivers

### ISSUE THREAD

**Issue by Mailaender** [flathub/net.openra.OpenRA#7]
I probably should have posted https://github.com/OpenRA/OpenRA/issues/17040 here instead as it works fine using the AppImages. Running `flatpak install flathub org.freedesktop.Platform.GL.nvidia` didn't help.

**Comment by Unrud** [comment]
Check ``flatpak list | grep nvidia``. It should output something like:

```
nvidia-390-129	org.freedesktop.Platform.GL.nvidia-390-129		1.4	i386	flathub	system
nvidia-390-129	org.freedesktop.Platform.GL.nvidia-390-129		1.4	x86_64	flathub	system
nvidia-390-129	org.freedesktop.Platform.GL32.nvidia-390-129		1.4	x86_64	flathub	system
```

The version of the nvidia driver must match the version of the host driver.

> Running ``flatpak install flathub org.freedesktop.Platform.GL.nvidia`` didn't help.

``flatpak update`` should take care of installing the correct nvidia driver.

**Comment by Mailaender** [comment]
`flatpak update` did fix that. It seems updating / installing via KDE Discover does not pull all the dependencies on openSUSE 15.1. Sorry for the false alarm.
